version: "3.9"
   
services:
    db:
        image: postgres
        restart: always
        volumes:
            - dev-db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - mynetwork
    web1:
        hostname: djangoapp1
        build: .
        restart: always
        entrypoint: ["sh", "/app/entrypoint.sh"]
        volumes:
            - .:/app
            - static-data:/vol/web
        ports:
            - "8001:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=1
            - DJANGO_SECRET_KEY=changeme
        depends_on:
            - db
        networks:
            - mynetwork
    web2:
        hostname: djangoapp2
        build: .
        restart: always
        entrypoint: ["sh", "/app/entrypoint.sh"]
        volumes:
            - .:/app
            - static-data:/vol/web
        ports:
            - "8002:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=1
            - DJANGO_SECRET_KEY=changeme
        depends_on:
            - db
        networks:
            - mynetwork
    web3:
        hostname: djangoapp3
        build: .
        restart: always
        entrypoint: ["sh", "/app/entrypoint.sh"]
        volumes:
            - .:/app
            - static-data:/vol/web
        ports:
            - "8003:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=1
            - DJANGO_SECRET_KEY=changeme
        depends_on:
            - db
        networks:
            - mynetwork
    proxy:
        build:
            context: ./proxy
        restart: always
        ports:
            - "80:80"
        volumes:
            - static-data:/vol/web
        depends_on:
            - web1
            - web2
            - web3
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

volumes:
    dev-db-data:
    static-data: