version: "3.9"
   
services:
    db:
        image: postgres
        volumes:
            - dev-db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        entrypoint: ["sh", "/app/entrypoint.sh"]
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=1
            - DJANGO_SECRET_KEY=changeme
        depends_on:
            - db
volumes:
    dev-db-data: