version: "3.9"
   
services:
    db:
        image: postgres
        restart: always
        volumes:
            - dev-db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        restart: always
        entrypoint: ["sh", "/app/entrypoint.sh"]
        volumes:
            - .:/app
            - static-data:/vol/web
        ports:
            - "9000:9000"
        environment:
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DEBUG=1
            - DJANGO_SECRET_KEY=changeme
        depends_on:
            - db
    proxy:
        build:
            context: ./proxy
        restart: always
        depends_on:
            - web
        ports:
            - 80:8000
        volumes:
            - static-data:/vol/static

volumes:
    dev-db-data:
    static-data: